### ISSUE TITLE
Dockerize Tracking Service

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/tracking-service#10]
**Is your feature request related to a problem? Please describe.**
See current docker installation. Let's update the installation to use Docker to spin up the service.

**Comment by jordanpadams** [comment]
:calendar: december status: added to build per availability of new personnel

**Comment by al-niessner** [comment]
To complete this as dockerized, do you want the docker container when run to execute internal to the container `mvn site:run` or to run tomcat with the WAR in the webapp directory? If the latter, then is there a configuration that you would like burned into the docker image?

**Comment by jordanpadams** [comment]
@al-niessner the latter. I think we just want the docker container to assume the WAR has been built with maven (WAR is in target directory), copy it to it's expected location in the Docker tomcat, and start it up. Per the config, I think the only non-standsrd thing we want is a non-standard port for Tomcat to avoid collisions on the standard tomcat where it is deployed. It looks like there are a couple maven plugins out there, but I don't think it's necessary.

@tloubrieu-jpl thoughts? Should we maybe ping the SAs for what they would hope the default config would be for any tomcats we deploy in docker containers?

**Comment by al-niessner** [comment]
For mapping ports, it is simpler to not change it in the docker image but to use the --port switch on the docker run to remap it. Those that expect to find it at 8080 will but those that need it elsewhere can do so without having to change and rebuild.

**Comment by tloubrieu-jpl** [comment]
I don't have experience in tomcat application deployed on docker yet but it sounds like we can used a tomcat based docker image as described here https://medium.com/@pra4mesh/deploy-war-in-docker-tomcat-container-b52a3baea448

**Comment by jordanpadams** [comment]
@al-niessner sounds good. Let's just be sure to include that flag in the installation docs in the maven site docker installation procedure

**Comment by al-niessner** [comment]
That is a re-usable tomcat. I did not think that is what you wanted. I thought you wanted an encapsulated tracking-service that could be deployed and simply run. Whatever run means.

Frankly, as simple as it is to install tomcat with a specific WAR file, there is not a lot of room for a reusable tomcat image to be more useful. Might even be less depending of the effort to maintain a shareable vault of WARs.

**Comment by tloubrieu-jpl** [comment]
The blog instructions sounded like what we wanted to do to have the service running in docker from the war which is produced by the current build process, but I might have missed something. @al-niessner you can see what is most appropriate since you have your hands dirty in it. Thanks.

**Comment by al-niessner** [comment]
I have two Dockerfiles building and mostly tested. One to build the local repo on disk. This one builds, runs, and tested as much as I can (see above comments). The other builds a release. Unfortunately, the only release is 0.5.0 which needs to have its POM updated for it to work.

I am going to try and release my work in [my fork](https://github.com/al-niessner/tracking-service/tree/dockerize) to complete the release dockerfile build and run tests. See [my fork](https://github.com/al-niessner/tracking-service/tree/dockerize)  for what all this docker stuff means as I have already updated the README and the docker stuff is at the bottom -- tell me what text you like better for the README.

If I cannot do the release in [my fork](https://github.com/al-niessner/tracking-service/tree/dockerize), then I am going to need to release a 0.5.1 (or some number) in this repo after merging in my changes via pull request and then test/repair after that.

Lastly, will need to put a warning on the 0.5.0 release that it is not docker friendly.
