### ISSUE TITLE
Add mysql database to docker deployment

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/tracking-service#14]
http://localhost:8080/tracking
 
When we click  on links in  http://localhost:8080/tracking it generates errors like:
 
 
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
                at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
                at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
                at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
                at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
                at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
                at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
                at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
                at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
                at gov.nasa.pds.tracking.tracking.db.DBConnector.getConnection(DBConnector.java:88)
                at gov.nasa.pds.tracking.tracking.db.ProductDao.getProductsOrderByTitle(ProductDao.java:111)
                at gov.nasa.pds.tracking.tracking.jsoninterfaces.JSONBasedProducts.defaultProducts(JSONBasedProducts.java:55)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke

It sounds like a database is missing in the back-end. This should be part of the docker deployment.

**Comment by al-niessner** [comment]
Simple to add, but complicated to add correctly. mysql is pretty insecure with lots of remote root stuff and no passwords. Do you want the insecure version or do you want the security patched version. If the latter will need passwords, strength of allowed passwords, root access from where, and a privilege table to duplicate.

Oh, and the name of the database that tracking will be using.

**Comment by jordanpadams** [comment]
@al-niessner the schema is out at `src/main/resources/schema/`. for permissions, let's keep them trivial for the time being since mysql is in its own container, but we can make it more secure down the road.

**Comment by tloubrieu-jpl** [comment]
@al-niessner 
one 'update'  and 'status' or end-point can be requested as explained in the `mvn site:run` operations.

**Comment by al-niessner** [comment]
@tloubrieu-jpl 
Is it possible to tell tracking services what database, username, and password to use when trying to communicate with mysql or is this all hardcoded?

**Comment by jordanpadams** [comment]
@al-niessner i doubt @tloubrieu-jpl will have any clue and neither do I :-) . you may need to poke around in the code to figure out how it is trying to make its connections

**Comment by tloubrieu-jpl** [comment]
@al-niessner yes I confirm I don't know, this version of tracking service was developed before I started on PDS... I would need to go in the code to see that, can you do it ?

**Comment by tloubrieu-jpl** [comment]
The tracking service needs to use a different user/password to connect the external container hosting mysql.

**Comment by al-niessner** [comment]
In the docker concept, do you expect that people will download the docker image and then run it or do you think they will build it?

The mysql parameters are fixed in a property file. If people build then they will have the opportunity to change them. If they download the image, not so much. It can be done through mounts but this really complicates the explanation of howto.

For now, I am leaving it as one of these two options. However, in the future it might be simpler/better to look at the environment variables first then the properties. It would allow for more run-time configuration while maintaining a just-usable version locally.

**Comment by jordanpadams** [comment]
@al-niessner i think having this information in the pre-built docker image is fine for now. however, we just need to make sure no mysql login information makes it into the Github repo. we should just include in our build instructions to contact pds-dev@jpl.nasa.gov to get the information to update that file.

@tloubrieu-jpl thoughts?

**Comment by al-niessner** [comment]
ENVs did not work because of tomcat spawning or cleansing. Either way, ENVs are not helping.

The mysql login stuff is already smattered through this repo. Trying hard to make it not so hardcoded.

**Comment by al-niessner** [comment]
Could not test via curl. Just get back a lot of complaints about ill formed request. The documentation from mvn site:run does not contain any examples and is a little too sparse for me to figure out by typing random characters.

For instance, tried this:

````
curl -X POST ${base_url}/html/doi/add?id=urn:fred:flinstone&version=2.0&site_url=no_way&emal=wilma&comment=test&doi=37373737
```

Did not work. Thought maybe I needed to repreat myself so tried:

```
curl -X POST ${base_url}/html/37373737/add?id=urn:fred:flinstone&version=2.0&site_url=no_way&emal=wilma&comment=test&doi=37373737
```

Both of which result in this message:

```
The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
```

**Comment by tloubrieu-jpl** [comment]
Sorry for my late contribution here, regarding sensitive data in docker container, it is recommanded to have them added at run time, for example though a mounted volume. I've just read that which seems like a good guide https://www.ctl.io/developers/blog/post/tutorial-protecting-sensitive-info-docker 

So we could mount externally the property file ?

**Comment by al-niessner** [comment]
I should have been more clear. All sensitive information was in this repository prior to docker. The changes for docker have allowed the extraction of the database related sensitive information.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner, I am testing this ticket now. Do you have instruction on how to handle the tracking service docker with an external docker mysql ?

Thanks

**Comment by al-niessner** [comment]
This [README.md](https://github.com/al-niessner/tracking-service/tree/issue_14) should have all the directions. You have to follow the preparation steps to prep the external mysql.

**Comment by tloubrieu-jpl** [comment]
Thank you @al-niessner  that is what I was looking for.

**Comment by tloubrieu-jpl** [comment]
@al-niessner the traking service does not start properly, I am having this error:

Failed to create work directory [/var/lib/tomcat9/work/Catalina/localhost/tracking] for context [/tracking]
<2>Failed to detect ServletContainerInitializers for context with name [/tracking]
<2>java.nio.file.FileSystemException: /tmp/jar_cache17933767627034334425.tmp: Read-only file system
<2>    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
<2>    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
<2>    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
<2>    at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
<2>    at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
<2>    at java.base/java.nio.file.Files.createFile(Files.java:648)
<2>    at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
<2>    at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
<2>    at java.base/java.nio.file.Files.createTempFile(Files.java:913)
<2>    at java.base/sun.net.www.protocol.jar.URLJarFile$1.run(URLJarFile.java:216)
<2>    at java.base/sun.net.www.protocol.jar.URLJarFile$1.run(URLJarFile.java:214)
<2>    at java.base/java.security.AccessController.doPrivileged(Native Method)
<2>    at java.base/sun.net.www.protocol.jar.URLJarFile.retrieve(URLJarFile.java:213)
<2>    at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:74)
<2>    at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
<2>    at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
<2>    at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
<2>    at java.base/java.net.URL.openStream(URL.java:1140)
<2>    at org.apache.catalina.startup.WebappServiceLoader.parseConfigFile(WebappServiceLoader.java:179)
<2>    at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:110)
<2>    at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1669)
<2>    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1137)
<2>    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:774)
<2>    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:301)
<2>    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
<2>    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5051)
<2>    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
<2>    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
<2>    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
<2>    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
<2>    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
<2>    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
<2>    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
<2>    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
<2>    at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
<2>    at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
<2>    at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
<2>    at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
<2>    at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
<2>    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
<2>    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
<2>    at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
<2>    at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
<2>    at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
<2>    at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
<2>    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
<2>    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
<2>    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
<2>    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
<2>    at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
<2>    at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
<2>    at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
<2>    at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
<2>    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
<2>    at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
<2>    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
<2>    at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
<2>    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
<2>    at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
<2>    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<2>    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
<2>    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<2>    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
<2>    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
<2>    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)


When I run:

docker run --rm \
           --network=pds \
           --publish 8082:8080 \
           --read-only --volume /Users/loubrieu/tmp/tracking-service/jdbc.properties:/etc/tracking_service/jdbc.properties \
           tracking_service:$(git rev-parse HEAD)

**Comment by tloubrieu-jpl** [comment]
@jordanpadams should Al or I go on working on that ? I believe we should since the tracking service is not starting properly but I am asking since Al already jumped to a different topic... I guess I could re-assigned that to me.

**Comment by al-niessner** [comment]
Please try without --read-only. I must not have updated the readme because
I could not get the read-only to work. Sorry about that.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl can you test it out real fast with the --read-only flag? If it spins up OK, I am ok with creating new tickets to track the issues and punt this for now as part of a larger focus on tracking service next build.
