### ISSUE TITLE
tracking front page does not keep tracking in relative anchor href

### ISSUE THREAD

**Issue by al-niessner** [NASA-PDS/tracking-service#18]
**Describe the bug**
The localhost:8080/tracking front page is a list of simple links that are of the form href="html/products". However when fully translated by the browser it becomes localhost:8080/html/products which causes a 404 error. Changing it to localhost:8080/tracking/html/products it loads.

**To Reproduce**
1. build docker image
2. run docker image without any CMDs
3. using your favorite browser goto localhost:8080 and click on any link

**Expected behavior**
Go to the available page.

** Version of Software Used**
docker version

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @al-niessner are we working on this now? or has this bug just been identified for tracking moving forward?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams , @al-niessner identified this bug and created the bug to keep track of it, he will work first on the mysql container integration. I did not look at this bug either yet, we can move it to next sprint maybe.

**Comment by tloubrieu-jpl** [comment]
I am pretty sure it did not happen with the first version of container that @al-niessner wrote.

**Comment by al-niessner** [comment]
If the initial URL is localhost:8080/tracking then this problem manifests. If it is localhost:8080/tracking/ then it works as expected.

**Comment by al-niessner** [comment]
Could not test via curl. Just get back a lot of complaints about ill formed request. The documentation from `mvn site:run` does not contain any examples and is a little too sparse for me to figure out by typing random characters.

**Comment by tloubrieu-jpl** [comment]
Good, I think that is good enough for now, thanks Al.

Conclusion, the tracking service application must be called with end-point localhost:8080/tracking/
